Sample code for Copilot Studio bots
microsoft/Dynamics365-Apps-Samples pull request #95
Opened 2024-11-25 09:27 UTC by neeranelli

2024-11-25 10:52 UTC, shubhadaj approved these changes

2024-11-25 18:23 UTC, JimDaly commented
This repository should be for sample code only.

Since this is only a zip file for customers to download, it should be distributed with other downloadable resources.   For example: https://download.microsoft.com/download/8/E/3/8E3279FE-7915-48FE-A68B-ACAFB86DA69C/MetadataBrowser_3_0_0_5_managed.zip

I've forwarded you information in chat about how to do this.

2024-11-25 23:38 UTC, JimDaly requested changes
As mentioned, we shouldn't use GitHub to distribute binary files. Use Download Center for that.

But if this managed solution supports a scenario for sample code, please include a README that explains the code and how this solution resource supports it, similar to https://github.com/microsoft/PowerApps-Samples/blob/master/model-driven-apps/custom-connectors/SecondaryRecordSource/solution/README.md

2024-11-26 08:01 UTC, neeranelli commented
Thank you for explanation, @JimDaly. I am closing this PR as it's no longer required.

2024-11-26 08:01 UTC, closed without merging